### PR TITLE
Add a toolbar with "M19G" title

### PR DESCRIPTION
**Pull request by kkimdev**
Issue: #24

Note: `ng test` fails with the following message.
```
Failed: Uncaught (in promise): Error: Template parse errors:
'md-toolbar' is not a known element:
```

Opened #26

### CODE REVIEW

**Comment by kkimdev** [comment]
Note: in general, `ng lint` `ng test` `ng e2e` should all pass.  We should have that check as a part of Travis CI ideally #14

**Comment by kkimdev** [comment]
@suj97 I won't merge this one but please take a look to use parts in your future changes, and close whenever it's no longer needed.

**Comment by suj97** [comment]
I didnt get you @kkimdev

**Comment by kkimdev** [comment]
@suj97 I mean, this PR is for adding a toobar, which is already done by #28 , but this has test code changes that will be still useful.

**Comment by suj97** [comment]
Ya! Got it.

**Comment by suj97** [comment]
Should i close this one then?

**Comment by kkimdev** [comment]
OK

**Pull request closed without merging**
